---
title: "Action alternatives & disruption factor"
output: html_document
date: "2023-03-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# load packages and read in data
```{r}

library(needs)
needs(tidyverse,
      psych,
      moments,
      sjPlot,
      DescTools,
      irr,
      readxl, 
      gridExtra,
      janitor,
      RColorBrewer,
      cowplot,
      zoo,
      apaTables)

# suppress "summarize" info. 
# if this line is ommitted, each table using the summarize function will be accompanied with a warning from the console
options(dplyr.summarise.inform = FALSE)

# SELF-REPORT DATA
df_sri <- 
  excel_sheets("data/coding_sri.xlsx") %>% 
  map_df(~read_xlsx("data/coding_sri.xlsx",.)) %>% 
  dplyr::select(ID, event, disruption_factor, confidence_factor) %>% 
  filter(!ID %in% c(141,
                    142,
                    204,
                    226), # filter relevant rows
         event %in% c("chatting")) %>%
  janitor::clean_names()

# # SJT CM
# df_sjt <- read_csv2(file = "data/SJT.csv",
#                     locale = locale(decimal_mark = ",")) %>% 
#   select(UI06_05,
#          SJT_KF_gek) %>%
#   filter(UI06_05 %in% c(101:126, 201:228),
#          !UI06_05 %in% c(204, 226)
#          ) %>% 
#   na.omit() %>% 
#   rename("id" = "UI06_05",
#          "sjt" = "SJT_KF_gek")


# ACTION ALTERNATIVES count
df_alternatives_count <- read_excel("data/coding_action_alternatives.xlsx") %>% 
  na.locf() %>% 
  janitor::clean_names() %>% 
  group_by(id) %>% 
  # mutate(mean_code = mean(code)) %>% 
  mutate(count = max(count)) %>% 
  distinct(count)

# ACTION ALTERNATIVES non-disruptive 
df_alternatives_nd <- read_excel("data/coding_action_alternatives.xlsx") %>% 
  na.locf() %>% 
  janitor::clean_names() %>% 
  select(id, code) %>% 
  mutate(nd = as.numeric(case_when(code > 3 ~ '0',
                                   code <= 3 ~ '1',
                                   TRUE ~ 'F'
                                   )
                         )
         ) %>% 
  select(id, nd) %>% 
  group_by(id) %>%
  summarise(nd = sum(nd))


# merge data frames
# put all data frames into list
df_list <- list(df_sri,
                # df_sjt,
                df_alternatives_count,
                df_alternatives_nd)

# merge all data frames in list
main <-
  df_list %>% reduce(full_join, by='id') %>%
  janitor::clean_names() %>%
  select(!event)

# replace NA with 0
main[is.na(main)] <- 0

main$id = ifelse(main$id < 200, "Novice","Expert")

# creating new column with absolute number of nd-alternatives
main_novice <- main %>%
  filter(id %in% c("Novice")) %>% 
  mutate(percent_nd = round((nd/count),
                            digits = 2)
         )

# creating new column with absolute number of nd-alternatives
main_expert <- main %>%
  filter(id %in% c("Expert")) %>% 
  mutate(percent_nd = round((nd/count),
                            digits = 2)
         )

# merge novice & expert data frame
main <- rbind(main_expert, main_novice)


```

# descriptives & plots
```{r}
# disruption factor
describeBy(main$disruption_factor, main$id)
plot_disrup <- boxplot(disruption_factor ~ id, data = main)

# confidence factor
describeBy(main$confidence_factor, main$id)
plot_disrup <- boxplot(confidence_factor ~ id, data = main)

# # sjt cm
# describeBy(main$sjt, main$id)
# plot_disrup <- boxplot(sjt ~ id, data = main)

# action alternatives - count
describeBy(main$count, main$id)
plot_action_count <- boxplot(count ~ id, data = main)
  
# action alternatives - non disruptive alternatives (absolute score)
describeBy(main$nd, main$id)
plot_action_quality <- boxplot(nd ~ id, data = main)

# action alternatives - non disruptive alternatives (relative score)
describeBy(main$percent_nd, main$id)
plot_action_quality <- boxplot(percent_nd ~ id, data = main)

# # frequencies
# main %>% 
#   group_by(id) %>% 
#   summarise(disruption_factor = n(),
#             confidence_factor = n(),
#             count = n(),
#             nd = n(),
#             percent_nd = n())
# 
# table(main$disruption_factor)
# table(main$confidence_factor)
# table(main$count)
# table(main$nd)
# table(main$percent_nd)

```

# disruption factor x count of action alternatives
```{r}
main %>% 
  filter(!is.na(disruption_factor) | !is.na(count)) %>% 
  # filter(id %in% c("Novice")) %>% 
  ggplot(mapping = aes(x = disruption_factor,
                       y = count,
                       colour = id
                       )
         ) +
  geom_point() + 
  geom_smooth(method = "lm",
              se = TRUE) +
  scale_color_viridis_d() +
  labs(x = "disruption Factor",
       y = "Count of action alternatives") +
  theme_cowplot()

```

# disruption factor x non-disruptive action alternatives
```{r}
main %>% 
  filter(!is.na(disruption_factor) | !is.na(percent_nd)) %>% 
  # filter(id %in% c("Novice")) %>% 
  ggplot(mapping = aes(x = disruption_factor,
                       y = percent_nd,
                       colour = id
                       )
         ) +
  geom_point() + 
  geom_smooth(method = "lm",
              se = TRUE) +
  scale_color_viridis_d() +
  labs(x = "disruption Factor",
       y = "Non-disruptive action alternatives") + 
  theme_cowplot()

```

# sjt x count of action alternatives
```{r}
main %>% 
  filter(!is.na(sjt) | !is.na(count)) %>% 
  # filter(id %in% c("Novice")) %>% 
  ggplot(mapping = aes(x = sjt,
                       y = count,
                       colour = id
                       )
         ) +
  geom_point() + 
  geom_smooth(method = "lm",
              se = TRUE) +
  scale_color_viridis_d() +
  labs(x = "SJT Classroom Management",
       y = "Count of action alternatives") +
  theme_cowplot()

```

# sjt x non-disruptive action alternatives
```{r}
main %>% 
  filter(!is.na(sjt) | !is.na(nd)) %>% 
  # filter(id %in% c("Novice")) %>% 
  ggplot(mapping = aes(x = sjt,
                       y = nd,
                       colour = id
                       )
         ) +
  geom_point() + 
  geom_smooth(method = "lm",
              se = TRUE) +
  scale_color_viridis_d() +
  labs(x = "SJT Classroom Management",
       y = "Non-disruptive action alternatives") + 
  theme_cowplot()

```

# t-test and effect size
```{r}

### action alternatives count
# t-test for expertise differences
t.test(x = main$count[main$id == "Expert"],
       y = main$count[main$id == "Novice"],
       var.equal = TRUE)

# effect size for expertise differences
CohenD(x = main$count[main$id == "Expert"],
       y = main$count[main$id == "Novice"],
       na.rm = TRUE)

### action alternatives non-disruptive absolute score
# t-test for expertise differences
t.test(x = main$nd[main$id == "Expert"],
       y = main$nd[main$id == "Novice"],
       var.equal = TRUE)

# effect size for expertise differences
CohenD(x = main$nd[main$id == "Expert"],
       y = main$nd[main$id == "Novice"],
       na.rm = TRUE)

### action alternatives non-disruptive relative score
# t-test for expertise differences
t.test(x = main$percent_nd[main$id == "Expert"],
       y = main$percent_nd[main$id == "Novice"],
       var.equal = TRUE)

# effect size for expertise differences
CohenD(x = main$percent_nd[main$id == "Expert"],
       y = main$percent_nd[main$id == "Novice"],
       na.rm = TRUE)

#### disruption factor
# t-test for expertise differences
t.test(x = main$disruption_factor[main$id == "Expert"],
       y = main$disruption_factor[main$id == "Novice"],
       var.equal = TRUE)

# effect size for expertise differences
CohenD(x = main$disruption_factor[main$id == "Expert"],
       y = main$disruption_factor[main$id == "Novice"],
       na.rm = TRUE)

#### confidence factor
# t-test for expertise differences
t.test(x = main$confidence_factor[main$id == "Expert"],
       y = main$confidence_factor[main$id == "Novice"],
       var.equal = TRUE)

# effect size for expertise differences
CohenD(x = main$confidence_factor[main$id == "Expert"],
       y = main$confidence_factor[main$id == "Novice"],
       na.rm = TRUE)


```

# pearson correlation

```{r}

# Korrelationstabelle nach APA-Standards
head(main)

# Subset anlegen nur mit Variablen == Experts
main %>%
  filter(id == "Expert") %>% 
  select(count, 
         nd,
         percent_nd,
         disruption_factor, 
         confidence_factor) -> corr_subset_expert

apa.cor.table(corr_subset_expert, filename = "correlation_experts.doc")

# Subset anlegen nur mit Variablen == Novices
main %>%
  filter(id == "Novice") %>% 
  select(count, 
         nd,
         percent_nd,
         disruption_factor, 
         confidence_factor) -> corr_subset_novice

apa.cor.table(corr_subset_novice, filename = "correlation_novices.doc")

# Subset anlegen nur mit Variablen overall
main %>%
  select(count, 
         nd,
         percent_nd,
         disruption_factor, 
         confidence_factor) -> corr_subset_overall

apa.cor.table(corr_subset_overall, filename = "correlation_overall.doc")



###################################################

# novices: correlation between disruption factor and count
main %>% 
  filter(id %in% c("Novice")) -> corr.nov

nov_disrup_count_corr <- cor.test(corr.nov$disruption_factor, 
                                 corr.nov$count, 
                                 method=c("pearson"),
                                 adjust="holm")
print(nov_disrup_count_corr, 
      short = F)

# experts: correlation between disruption factor and count
main %>% 
  filter(id %in% c("Expert")) -> corr.exp

exp_disrup_count_corr <- cor.test(corr.exp$disruption_factor, 
                                 corr.exp$count, 
                                 method=c("pearson"),
                                 adjust="holm")
print(exp_disrup_count_corr, 
      short = F)

# full sample: correlation between disruption factor and count
full_disrup_count_corr <- corr.test(main$disruption_factor, 
                                   main$count, 
                                   method=c("pearson"), 
                                   adjust="holm")
print(full_disrup_count_corr,
      short = F)


###################################################

# novices: correlation between disruption factor and non-disruptive alternatives (absolute score)
nov_disrup_abs.nd_corr <- cor.test(corr.nov$disruption_factor,
                              corr.nov$nd, 
                              method=c("pearson"),
                              adjust="holm")
print(nov_disrup_abs.nd_corr, 
      short = F)

# experts: correlation between disruption factor and non-disruptive alternatives (absolute score)
exp_disrup_abs.nd_corr <- cor.test(corr.exp$disruption_factor,
                              corr.exp$nd, 
                              method=c("pearson"),
                              adjust="holm")
print(exp_disrup_abs.nd_corr,
      short = F)

# full sample: correlation between disruption factor and non-disruptive alternatives (absolute score)
full_disrup_abs.nd_corr <- corr.test(main$disruption_factor, 
                                main$nd, method=c("pearson"),
                                adjust="holm")
print(full_disrup_abs.nd_corr,
      short = F)  


###################################################

# novices: correlation between disruption factor and non-disruptive alternatives (relative score)
nov_disrup_nd_corr <- cor.test(corr.nov$disruption_factor,
                              corr.nov$percent_nd, 
                              method=c("pearson"),
                              adjust="holm")
print(nov_disrup_nd_corr, 
      short = F)

# experts: correlation between disruption factor and non-disruptive alternatives (relative score)
exp_disrup_nd_corr <- cor.test(corr.exp$disruption_factor,
                              corr.exp$percent_nd, 
                              method=c("pearson"),
                              adjust="holm")
print(exp_disrup_nd_corr,
      short = F)

# full sample: correlation between disruption factor and non-disruptive alternatives (relative score)
full_disrup_nd_corr <- corr.test(main$disruption_factor, 
                                main$percent_nd, method=c("pearson"),
                                adjust="holm")
print(full_disrup_nd_corr,
      short = F)  

###################################################

# novices: correlation between count and non-disruptive alternatives (absolute score)
nov_count_abs.nd_corr <- cor.test(corr.nov$count,
                              corr.nov$nd, 
                              method=c("pearson"),
                              adjust="holm")
print(nov_count_abs.nd_corr, 
      short = F)

# experts: correlation between count and non-disruptive alternatives (absolute score)
exp_count_abs.nd_corr <- cor.test(corr.exp$count,
                              corr.exp$nd, 
                              method=c("pearson"),
                              adjust="holm")
print(exp_count_abs.nd_corr,
      short = F)

# full sample: correlation between disruption factor and non-disruptive alternatives (absolute score)
full_count_abs.nd_corr <- corr.test(main$count, 
                                main$nd, 
                                method=c("pearson"),
                                adjust="holm")
print(full_count_abs.nd_corr,
      short = F)

###################################################

# novices: correlation between count and non-disruptive alternatives (relative score)
nov_count_nd_corr <- cor.test(corr.nov$count,
                              corr.nov$percent_nd, 
                              method=c("pearson"),
                              adjust="holm")
print(nov_count_nd_corr, 
      short = F)

# experts: correlation between count and non-disruptive alternatives (relative score)
exp_count_nd_corr <- cor.test(corr.exp$count,
                              corr.exp$percent_nd, 
                              method=c("pearson"),
                              adjust="holm")
print(exp_count_nd_corr,
      short = F)

# full sample: correlation between disruption factor and non-disruptive alternatives (relative score)
full_count_nd_corr <- corr.test(main$count, 
                                main$percent_nd, 
                                method=c("pearson"),
                                adjust="holm")
print(full_count_nd_corr,
      short = F)

###################################################


# # novices: correlation between sjt and count
# nov_sjt_count_corr <- cor.test(corr.nov$sjt,
#                               corr.nov$count, 
#                               method=c("pearson"),
#                               adjust="holm")
# print(nov_sjt_count_corr, 
#       short = F)
# 
# # experts: correlation between sjt and count
# exp_sjt_count_corr <- cor.test(corr.exp$sjt,
#                               corr.exp$count, 
#                               method=c("pearson"),
#                               adjust="holm")
# print(exp_sjt_count_corr,
#       short = F)
# 
# # full sample: correlation between sjt and count
# full_sjt_count_corr <- corr.test(main$sjt, 
#                                  main$count, 
#                                  method=c("pearson"), 
#                                  adjust="holm")
# print(full_sjt_count_corr, 
#       short = F)
# 
# 
# ###################################################
# 
# # novices: correlation between sjt and non-disruptive alternatives
# nov_sjt_nd_corr <- cor.test(corr.nov$sjt,
#                               corr.nov$nd, 
#                               method=c("pearson"),
#                               adjust="holm")
# print(nov_sjt_nd_corr, 
#       short = F)
# 
# # experts: correlation between sjt and non-disruptive alternatives
# exp_sjt_nd_corr <- cor.test(corr.exp$sjt,
#                               corr.exp$nd, 
#                               method=c("pearson"),
#                               adjust="holm")
# print(exp_sjt_nd_corr,
#       short = F)
# 
# 
# # full sample: correlation between sjt and non-disruptive alternatives
# full_sjt_nd_corr <- corr.test(main$sjt,
#                               main$nd,
#                               method=c("pearson"),
#                               adjust="holm")
# print(full_sjt_nd_corr,
#       short = F)

```


