---
title: "Analysis 19.04.2023"
author: "Peer Keßler"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, warning = FALSE)
```

```{r}
library(needs)
needs(ltm,
      xtable,
      broom,
      ppcor,
      jtools,
      lm.beta,
      janitor,
      lubridate,
      readxl,
      ggthemes,
      gridExtra,
      imputeTS,
      DescTools,
      cowplot,
      rstatix,
      ggpubr,
    #  lme4,
      lmerTest,
      viridis,
      gridExtra,
      gridtext,
      magrittr,
      PerformanceAnalytics,
      Hmisc,
      corrplot,
      tidyverse)

# disruption & confidence rating
df_rating <- 
  excel_sheets("data/Coding_SRI.xlsx") %>% 
  map_df(~read_xlsx("data/Coding_SRI.xlsx",.)) %>% # read in data with two sheets
  dplyr::select(ID, # select relevant columns 
         disruption_factor, # -99 = subject did not notice event; -100 = experimenter did not asked for event
         confidence_factor,
         event
         ) %>% 
  mutate(disruption_factor = ifelse(disruption_factor < 0,
                                    yes = NA,
                                    no = disruption_factor
                                    ),
         confidence_factor = ifelse(confidence_factor < 0,
                                   yes = NA,
                                   no = confidence_factor),
         event = as_factor(event)
         )

# demographic data
df_demo <- 
  read_excel("./data/data_empschul_labor_lehrperson.xlsx") %>% # read in excel 
  transmute(ID = LI06_05, # select and rename relevant columns 
            gender = factor(LI02_01_1,
                            levels = 1:2,
                            labels = c("male","female")
                            ),
            age = LI03_01, # 1 = male; 2 = female
            teaching_experience = LI04_01)

# merge two data frames by ID 
df_merge <- merge(df_demo,
                  df_rating,
                  by = "ID") %>% 
  filter(!ID %in% c("126", # exclude cases with no fitbit data (to check see data Heart Rate)
                    "132")
         )

# rm(list = c("df_demo","df_rating"))


data_path <- "./data/heart_rate_data"

main <-
map(.x = dir(path = data_path,
             pattern = ".csv"),
    ~ read_csv(file.path(data_path, .), 
               id = "id",
               col_types = c("t","n")
               ) %>% 
  mutate(time = .$Time - min(.$Time),
         time = as.numeric(time),
         heart_rate = `Heart Rate`,
         ID = id,
         time_span = case_when(str_detect(string = id, pattern = "_a") ~ "end",
                               str_detect(string = id, pattern = "_m") ~ "teaching",
                               str_detect(string = id, pattern = "_p") ~ "preparation",
                               str_detect(string = id, pattern = "_s") ~ "post",
                               str_detect(string = id, pattern = "_i") ~ "interview",
                               TRUE ~ "overall"
                               ),
         ID = str_extract(string = ID,
                          pattern = "[:digit:]{3}"),
         ID = as.numeric(ID)
      ) %>%
      # filter(time <= 600) %>% # filter for 10min intervals
    filter(time <= 7200) %>% # filter for 2 hours 30min (maximal duration of study)
    dplyr::select(!c("Time","Heart Rate","id"))
    ) %>%
  bind_rows()

main <-
  left_join(main, df_merge,
            by = "ID")

main <- 
  main %>% 
  dplyr::select("time", "heart_rate", "ID", "time_span") %>% 
  distinct() %>% 
  group_by(ID) %>% 
  summarize(mean_heart = mean(heart_rate),
            sd_heart = sd(heart_rate)) %>%
  ungroup() %>% 
  right_join(x = .,
             y = main,
             by = "ID") %>% 
  mutate(heart_rate_std = (heart_rate - mean_heart)/
           sd_heart) %>% 
  filter(!(time_span == "teaching" & time > 600)) 



```

# Graph

```{r fig.width = 10,results='hide',fig.keep='all'}
loess_plot_overall <-
  main %>% 
  filter(time_span == "overall") %>%
  dplyr::select("ID","time_span", "time","heart_rate_std") %>% 
  distinct() %>% 
  ggplot(mapping = aes(x = time,
                       y = heart_rate_std
                       )
         ) +
  # geom_point(alpha = 0.05) + 
  geom_smooth(se = FALSE,
              size = 0.5,
              colour = "black") +
  scale_color_viridis_d(option = "A",
                        end = 0.8) +
  scale_linetype_manual(values = c(1, 6)) +
  scale_x_continuous(expand = c(0, NA),
                     breaks = seq(0, 9000, 600)) +
  scale_y_continuous(breaks = seq(-1, 1, 0.5)) + 
  labs(x = "Time (in Seconds)",
       y = "") +
  ggtitle("Overall Course of Average Heartrate") +
  theme_apa() + 
  theme(axis.title.y = element_blank())

lm_plot_phases <-
  main %>% 
  filter(time_span != "overall") %>%
  dplyr::select("ID","time_span", "time","heart_rate_std") %>% 
  mutate(time_span = factor(time_span,
                            levels = c("preparation","teaching","post","interview","end"),
                            labels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase"))) %>% 
  distinct() %>% 
  ggplot(mapping = aes(x = time,
                       y = heart_rate_std
                       )
         ) +
  # geom_point(alpha = 0.05) + 
  geom_smooth(method = "lm",
              se = FALSE,
              size = 0.5,
              colour = "black") +
  scale_color_viridis_d(option = "A",
                        end = 0.8) +
  scale_linetype_manual(values = c(1, 6)) +
  # scale_x_continuous(expand = c(0, NA),
  #                    breaks = seq(0, 9000, 600)) +
  #scale_y_continuous(breaks = seq(0, 160, 5)) + 
  labs(x = "Time (in Seconds)",
       y = "",
       subtitle = "Linear Estimation") +
  theme_apa() +
  theme(axis.title.y = element_blank()) +
  facet_grid(cols = vars(time_span),
             scales = "free_x")

ki_plot_phases <-
  main %>% 
  filter(time_span != "overall") %>%
  dplyr::select("ID","time_span", "time","heart_rate_std") %>% 
  mutate(time_span = factor(time_span,
                            levels = c("preparation","teaching","post","interview","end"),
                            labels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase"))) %>% 
  distinct() %>%
  group_by(time_span) %>% 
  summarise(z_mean = mean(heart_rate_std),
            z_sd = sd(heart_rate_std),
            z_t = qt(p = 0.01 / 2,      # 0.01 KI
               df = n() - 1,
               lower.tail = F
               ),
            z_error = z_sd / sqrt(n()),
            lower = z_mean - z_t * z_error,
            upper = z_mean + z_t * z_error,
            ) %>% 
  ungroup() %>% 
  ggplot(mapping = aes(x = factor(0),
                       y = z_mean)) + 
  geom_point() +
  geom_errorbar(mapping = aes(ymin = lower,
                              ymax = upper),
                width = 0.2) +
  geom_hline(yintercept = 0,
             linetype = "dashed") +
  labs(subtitle = "1% Confidence Intervall",
       x = "") +
  facet_grid(cols = vars(time_span)) +
  theme_apa() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank())


text_y <- text_grob("Average Heart Rate (Standardized)",
                   rot = 90)

plot_overall <-
  grid.arrange(loess_plot_overall, lm_plot_phases, ki_plot_phases,
               ncol = 1,
               left = text_y
               )

plot_overall
```

# Correlation



```{r, warning=FALSE}
cache_corr <- 
  main %>% 
  clean_names() %>% 
  group_by(id) %>% 
  dplyr::summarize(`Mean Heartrate` = mean_heart,
            `Age` = age,
            `Teaching Experience` = teaching_experience,
            `Disruption Factor` = mean(disruption_factor, na.rm = T),
            `Confidence Factor` = mean(confidence_factor, na.rm = T)
            ) %>% 
  ungroup() %>% 
  distinct() %>% 
  select(!"id")

res <- rcorr(as.matrix(cache_corr))

knitr::kable(res[1], caption = "Pearson r")
knitr::kable(res[3], caption = "p Value")
```

```{r warning=FALSE,message=FALSE,error=FALSE}
corrplot(res$r, type="upper", order="hclust", sig.level = 0.05)
```


# Slopes, Intercepts

```{r}
df_regression <- 
  main %>% 
  filter(time_span != "overall") %>%
  dplyr::select("ID", "time_span","time","heart_rate_std") %>% 
  distinct() %>% 
  mutate(ID = as_factor(ID),
         Phase = factor(time_span,
                           levels = c("preparation","teaching","post","interview","end"),
                            labels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase")
                           ))

table_data <- 
  df_regression %>% 
#  mutate(time = time * 60) %>% 
  split(.$Phase) %>% 
  map(~ lmer(formula = heart_rate_std ~ 1 + time + (1 + time | ID),
       data = .
       )
      ) %>%
  map(~ tibble(time_span = names(.),
               intercept = fixef(.)[[1]],
               intercept_sd = VarCorr(.) %>% as_tibble() %>% .[1,5],
               intercept_p = coef(summary(.))[1, 5],
               slope = fixef(.)[[2]],
               slope_sd = VarCorr(.) %>% as_tibble() %>% .[2,5],
               slope_p = coef(summary(.))[2, 5]
               )
      ) %>% 
  bind_rows(.id = "Phase") %>% 
  transmute(Phase = factor(Phase,
                           levels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase")
                           ),
            n = NA,
            `Mean(Intercept)` = round(intercept, digits = 3),
            `SD(Intercept)` = round(intercept_sd$sdcor, digits = 3),
            `p-Value (Intercept)` = round(intercept_p, digits = 3),
            `Mean(Slope)` = round(slope, digits = 3),
            `SD(Slope)` = round(slope_sd$sdcor, digits = 3),
            `p-Value (Slope)` = round(slope_p, digits = 3)
            )

table_data$n[table_data$Phase == "Pre Teaching Phase"] <- df_regression %>% filter(Phase == "Pre Teaching Phase") %>% pull(heart_rate_std) %>% length()
table_data$n[table_data$Phase == "Teaching Phase"] <- df_regression %>% filter(Phase == "Teaching Phase") %>% pull(heart_rate_std) %>% length()
table_data$n[table_data$Phase == "Post Teaching Phase"] <- df_regression %>% filter(Phase == "Post Teaching Phase") %>% pull(heart_rate_std) %>% length()
table_data$n[table_data$Phase == "Interview Phase"] <- df_regression %>% filter(Phase == "Interview Phase") %>% pull(heart_rate_std) %>% length()
table_data$n[table_data$Phase == "End Phase"] <- df_regression %>% filter(Phase == "End Phase") %>% pull(heart_rate_std) %>% length()


table_data %>% 
  arrange(Phase) %>% 
knitr::kable(., caption = "Overview")
```

# t-Test (Teaching Phase vs. Interview Phase)

Results:

```{r}
cache1 <- 
  main %>% 
  dplyr::select("ID","time","heart_rate_std", "heart_rate", "time_span") %>% 
  distinct() %>% 
  mutate(ID = as_factor(ID)) %>% 
  split(.$time_span) %>% 
  map(~ lmer(formula = heart_rate_std ~ 1 + time + (1 + time | ID),
             data = .)) %>% 
  map(~ ranef(.)$ID %>% 
        as_tibble(., 
                  rownames = "ID"
                  ) %>% 
        clean_names()
      ) %>% 
  bind_rows(.,
            .id = "time_span")

cache2 <-  
  main %>% 
  dplyr::select("ID","time","heart_rate_std", "heart_rate","time_span") %>% 
  distinct() %>% 
  mutate(ID = as_factor(ID)) %>% 
  split(.$time_span) %>% 
  map(~ lmer(formula = heart_rate_std ~ 1 + time + (1 + time | ID),
             data = .)) %>% 
  map(~ summary(.) %>% 
        .$coefficients %>% 
        .[c(1,2)]) %>% 
  bind_rows(.,
            .id = "time_span") %>% 
  pivot_longer(
  cols = everything(),
  names_to = "time_span",
  values_to = "mean_value"
  )

df_test <- 
  tibble(mean_intercept = cache2$mean_value[1:6],
         mean_time = cache2$mean_value[7:12],
         time_span = cache2$time_span[1:6]) %>% 
  right_join(x = .,
             y = cache1,
             by = "time_span") %>% 
  transmute(time_span,
            intercept = mean_intercept + intercept,
            time = mean_time + time,
            id = id)

t.test(df_test$intercept[df_test$time_span == "teaching"],
       df_test$intercept[df_test$time_span == "interview"],
       paired = TRUE)

t.test(df_test$intercept[df_test$time_span == "teaching"],
       df_test$intercept[df_test$time_span == "end"],
       paired = TRUE)
```

Cohen D:

```{r}
CohenD(x = df_test$intercept[df_test$time_span == "teaching"],
       y = df_test$intercept[df_test$time_span == "interview"],
       pooled = T
       )

CohenD(x = df_test$intercept[df_test$time_span == "teaching"],
       y = df_test$intercept[df_test$time_span == "end"],
       pooled = T
       )
```

# Graphs for all Phases

```{r}
mods <-   
  df_regression %>% 
  split(.$time_span) %>% 
  map(~ lmer(formula = heart_rate_std ~ 1 + time + (1 + time | ID),
       data = .
       )
      )

graph_data <- 
  df_regression %>% 
  split(.$time_span) 

example <- list(mod = mods$preparation, data = graph_data$preparation)


list(`Preparation Phase` = list(name = "Preparation Phase", mod = mods$preparation, data = graph_data$preparation),
     `Teaching Phase` = list(name = "Teaching Phase", mod = mods$teaching, data = graph_data$teaching),
     `Post Teaching Phase` = list(name = "Post Teaching Phase",mod = mods$post, data = graph_data$post),
     `Interview Phase` = list(name = "Interview Phase",mod = mods$interview, data = graph_data$interview),
     `End Phase` = list(name = "End Phase",mod = mods$end, data = graph_data$end)
     ) %>% 
  map(~ ggplot(data = .$data,
               mapping = aes(x = time,
                             y = heart_rate_std,
                             group = ID)) +
        geom_line(mapping = aes(y = fitted(.$mod)),
                  color = "blue",
                  size = 1) +
        geom_point(alpha = 0.5,
                   size = 0.5) +
        labs(title = .$name,
             y = "Heart Rate (Standardized)",
             x = "Time (in Seconds)") +
        facet_wrap( ~ ID, nrow = 6) +
        theme_apa()
      )
```

# Different endings

```{r fig.width = 10,results='hide',fig.keep='all'}
df_survival <- 
  main %>% 
  filter(time_span == "overall") %>% 
  select("time","ID") %>% 
  distinct() %>% 
  group_by(ID) %>% 
  summarise(max_time = max(time)) %>% 
  ungroup()

df_survival_analysis <- 
  tibble(time = seq(max(df_survival$max_time),
              min(df_survival$max_time),
              by = -1),
         p = NA)

n <- length(df_survival$ID)

for (i in seq(min(df_survival$max_time),
              max(df_survival$max_time),
              by = 1)) {
  
  p <- 
    df_survival %>%
    filter(max_time >= i) %>%
    pull(max_time) %>%
    length(.)
  
  df_survival_analysis$p[df_survival_analysis$time == i] <- p/n
  
}

p_80 <- 
  df_survival_analysis %>% 
  filter(p > 0.8) %>% 
  pull(time) %>% 
  max(.)

p_90 <- 
  df_survival_analysis %>% 
  filter(p > 0.9) %>% 
  pull(time) %>% 
  max(.)
  

df_survival_analysis %>% 
  ggplot(mapping = aes(x = time,
                       y = p
                       )
         ) + 
  geom_line() +
  geom_hline(yintercept = 0.8,
             linetype = "dashed"
             ) +
  geom_hline(yintercept = 0.9,
             linetype = "dashed"
             ) +
  geom_vline(xintercept = p_80,
             linetype = "dashed"
             ) +
  geom_vline(xintercept = p_90,
             linetype = "dashed"
             ) +
  labs(x = "Time (in Seconds)",
       y = "Relative Frequency") +
  scale_x_continuous(breaks=c(4500, 5000, p_90, 5500, p_80, 6500, 7000)) +
  scale_y_continuous(breaks=c(0.25, 0.5, 0.75, 0.8, 0.9, 1)) +
  theme_apa()
```

```{r fig.width = 10,results='hide',fig.keep='all'}
loess_plot_data_90 <- 
  main %>% 
  filter(time_span == "overall" &
         time <= p_90) %>%
  dplyr::select("heart_rate", "ID", "time") %>% 
  distinct() %>% 
  group_by(ID) %>% 
  summarize(mean_heart = mean(heart_rate),
            sd_heart = sd(heart_rate)) %>%
  ungroup() %>% 
  right_join(x = .,
             y = distinct(select(main,
                          "ID","time_span", "time", "heart_rate"
                        )),
             by = "ID") %>% 
  mutate(heart_rate_std = (heart_rate - mean_heart)/
           sd_heart)

loess_plot_data_80 <- 
  main %>% 
  filter(time_span == "overall" &
         time <= p_80) %>%
  dplyr::select("heart_rate", "ID", "time") %>% 
  distinct() %>% 
  group_by(ID) %>% 
  summarize(mean_heart = mean(heart_rate),
            sd_heart = sd(heart_rate)
            ) %>%
  ungroup() %>%  
  right_join(x = .,
             y = distinct(select(main,
                          "ID","time_span", "time", "heart_rate"
                        )),
             by = "ID") %>%
  mutate(heart_rate_std = (heart_rate - mean_heart)/
           sd_heart)

loess_plot_data_all <- 
  main %>% 
  filter(time_span == "overall") %>%
  dplyr::select("heart_rate", "ID", "time") %>% 
  distinct() %>% 
  group_by(ID) %>% 
  summarize(mean_heart = mean(heart_rate),
            sd_heart = sd(heart_rate)
            ) %>%
  ungroup() %>%  
  right_join(x = .,
             y = distinct(select(main,
                          "ID","time_span", "time", "heart_rate"
                        )),
             by = "ID") %>%
  mutate(heart_rate_std = (heart_rate - mean_heart)/
           sd_heart)


ggplot(mapping = aes(x = time,
                            y = heart_rate_std
                            )) +
  geom_smooth(data = loess_plot_data_80,
              aes(color = "80%"),
              se = F
              ) +
  geom_smooth(data = loess_plot_data_90,
              aes(color = "90%"),
              se = F) +
  geom_smooth(data = loess_plot_data_all,
              aes(color = "Baseline"),
              linetype = "dashed",
              se = F) +
  labs(x = "Time (in Seconds)",
       y = "Average Heart Rate (Standardized)",
       color = "Legend") +
  scale_color_manual(values = c("80%" = "blue", "90%" = "red", "Baseline" = "black")) +
  theme_apa()
```

# Robustness

```{r fig.width = 10,results='hide',fig.keep='all'}
linear_plot_data_80 <- 
  main %>% 
  filter(time_span != "overall") %>%
  dplyr::select("ID","time_span", "time", "heart_rate") %>% 
  distinct() %>% 
  left_join(x = .,
            y = distinct(select(.data = loess_plot_data_80,
                       "ID", "mean_heart", "sd_heart")),
            by = "ID"
            ) %>% 
  mutate(heart_rate_std = (heart_rate - mean_heart)/
           sd_heart,
         Phase = factor(time_span,
                           levels = c("preparation","teaching","post","interview","end"),
                            labels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase")
                           )
         )

linear_plot_data_90 <- 
  main %>% 
  filter(time_span != "overall") %>%
  dplyr::select("ID","time_span", "time", "heart_rate") %>% 
  distinct() %>% 
  left_join(x = .,
            y = distinct(select(.data = loess_plot_data_90,
                       "ID", "mean_heart", "sd_heart")),
            by = "ID"
            ) %>% 
  mutate(heart_rate_std = (heart_rate - mean_heart)/
           sd_heart,
         Phase = factor(time_span,
                           levels = c("preparation","teaching","post","interview","end"),
                            labels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase")
                           )
         )

linear_plot_data_all <-
  main %>% 
  filter(time_span != "overall") %>%
  dplyr::select("ID","time_span", "time","heart_rate_std") %>% 
  distinct() %>% 
  mutate(Phase = factor(time_span,
                           levels = c("preparation","teaching","post","interview","end"),
                            labels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase")
                           ))

ggplot(mapping = aes(x = time,
                     y = heart_rate_std
                     )
       ) +
  # geom_point(alpha = 0.05) +
  geom_smooth(data = linear_plot_data_80,
              method = "lm",
              se = FALSE,
              size = 0.5,
              mapping = aes(color = "80%")
              ) +
  geom_smooth(data = linear_plot_data_90,
              method = "lm",
              se = FALSE,
              size = 0.5,
              mapping = aes(color = "90%")
              ) +
  geom_smooth(data = linear_plot_data_all,
              method = "lm",
              se = FALSE,
              size = 0.5,
              linetype = "dashed",
              mapping = aes(color = "Baseline")
              ) +
  scale_color_manual(values = c("80%" = "blue", "90%" = "red", "Baseline" = "black")) + 
  labs(x = "Time (in Seconds)",
       y = "Average Heart Rate (Standardized)",
       color = "") +
  facet_grid(cols = vars(Phase)) +
  theme_apa()
```



```{r}


loess_plot_overall <-
  main %>% 
  filter(time_span == "overall") %>%
  dplyr::select("ID","time_span", "time","heart_rate_std") %>% 
  distinct() %>% 
  ggplot(mapping = aes(x = time,
                       y = heart_rate_std
                       )
         ) +
  # geom_point(alpha = 0.05) + 
  geom_smooth(se = FALSE,
              size = 0.5,
              colour = "black") +
  scale_color_viridis_d(option = "A",
                        end = 0.8) +
  scale_linetype_manual(values = c(1, 6)) +
  scale_x_continuous(expand = c(0, NA),
                     breaks = seq(0, 9000, 600)) +
  scale_y_continuous(breaks = seq(-1, 1, 0.5)) + 
  labs(x = "Time (in Seconds)",
       y = "") +
  ggtitle("Overall Course of Average Heartrate") +
  theme_apa() + 
  theme(axis.title.y = element_blank())
```


t-Test mit Mittelwerten -> teaching vs. interview & teaching vs. end & interview vs. end

