---
title: "R Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, warning = FALSE)
```

```{r}
library(needs)
needs(ltm,
      xtable,
      broom,
      ppcor,
      jtools,
      lm.beta,
      janitor,
      lubridate,
      readxl,
      ggthemes,
      gridExtra,
      imputeTS,
      DescTools,
      cowplot,
      rstatix,
      ggpubr,
      lme4,
      lmerTest,
      viridis,
      gridExtra,
      gridtext,
      magrittr,
      PerformanceAnalytics,
      Hmisc,
      corrplot,
      tidyverse)

# disruption & confidence rating
df_rating <- 
  excel_sheets("data/Coding_SRI.xlsx") %>% 
  map_df(~read_xlsx("data/Coding_SRI.xlsx",.)) %>% # read in data with two sheets
  dplyr::select(ID, # select relevant columns 
         disruption_factor, # -99 = subject did not notice event; -100 = experimenter did not asked for event
         confidence_factor,
         event
         ) %>% 
  mutate(disruption_factor = ifelse(disruption_factor < 0,
                                    yes = NA,
                                    no = disruption_factor
                                    ),
         confidence_factor = ifelse(confidence_factor < 0,
                                   yes = NA,
                                   no = confidence_factor),
         event = as_factor(event)
         )

# demographic data
df_demo <- 
  read_excel("./data/data_empschul_labor_lehrperson.xlsx") %>% # read in excel 
  transmute(ID = LI06_05, # select and rename relevant columns 
            gender = factor(LI02_01_1,
                            levels = 1:2,
                            labels = c("male","female")
                            ),
            age = LI03_01, # 1 = male; 2 = female
            teaching_experience = LI04_01)

# merge two data frames by ID 
df_merge <- merge(df_demo,
                  df_rating,
                  by = "ID") %>% 
  filter(!ID %in% c("126", # exclude cases with no fitbit data (to check see data Heart Rate)
                    "132")
         )

# rm(list = c("df_demo","df_rating"))


data_path <- "./data/heart_rate_data"

main <-
map(.x = dir(path = data_path,
             pattern = ".csv"),
    ~ read_csv(file.path(data_path, .), 
               id = "id",
               col_types = c("t","n")
               ) %>% 
  mutate(time = .$Time - min(.$Time),
         time = as.numeric(time),
         heart_rate = `Heart Rate`,
         ID = id,
         time_span = case_when(str_detect(string = id, pattern = "_a") ~ "end",
                               str_detect(string = id, pattern = "_m") ~ "teaching",
                               str_detect(string = id, pattern = "_p") ~ "preparation",
                               str_detect(string = id, pattern = "_s") ~ "post",
                               str_detect(string = id, pattern = "_i") ~ "interview",
                               TRUE ~ "overall"
                               ),
         ID = str_extract(string = ID,
                          pattern = "[:digit:]{3}"),
         ID = as.numeric(ID)
      ) %>%
      # filter(time <= 600) %>% # filter for 10min intervals
    filter(time <= 7200) %>% # filter for 2 hours 30min (maximal duration of study)
    dplyr::select(!c("Time","Heart Rate","id"))
    ) %>%
  bind_rows()

main <-
  left_join(main, df_merge,
            by = "ID")

main <- 
  main %>% 
  dplyr::select("time", "heart_rate", "ID", "time_span") %>% 
  distinct() %>% 
  group_by(ID) %>% 
  summarize(mean_heart = mean(heart_rate),
            sd_heart = sd(heart_rate)) %>%
  ungroup() %>% 
  right_join(x = .,
             y = main,
             by = "ID") %>% 
  mutate(heart_rate_std = (heart_rate - mean_heart)/
           sd_heart) %>% 
  filter(!(time_span == "teaching" & time > 600)) 

```

# Graph

```{r fig.width = 10,results='hide',fig.keep='all'}
loess_plot_overall <-
  main %>% 
  filter(time_span == "overall") %>%
  dplyr::select("ID","time_span", "time","heart_rate_std") %>% 
  distinct() %>% 
  ggplot(mapping = aes(x = time,
                       y = heart_rate_std
                       )
         ) +
  # geom_point(alpha = 0.05) + 
  geom_smooth(se = FALSE,
              size = 0.5,
              colour = "black") +
  scale_color_viridis_d(option = "A",
                        end = 0.8) +
  scale_linetype_manual(values = c(1, 6)) +
  scale_x_continuous(expand = c(0, NA),
                     breaks = seq(0, 9000, 600)) +
  scale_y_continuous(breaks = seq(-1, 1, 0.5)) + 
  labs(x = "Time (in Seconds)",
       y = "") +
  ggtitle("Overall Course of Average Heartrate") +
  theme_apa() + 
  theme(axis.title.y = element_blank())

lm_plot_phases <-
  main %>% 
  filter(time_span != "overall") %>%
  dplyr::select("ID","time_span", "time","heart_rate_std") %>% 
  mutate(time_span = factor(time_span,
                            levels = c("preparation","teaching","post","interview","end"),
                            labels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase"))) %>% 
  distinct() %>% 
  ggplot(mapping = aes(x = time,
                       y = heart_rate_std
                       )
         ) +
  # geom_point(alpha = 0.05) + 
  geom_smooth(method = "lm",
              se = FALSE,
              size = 0.5,
              colour = "black") +
  scale_color_viridis_d(option = "A",
                        end = 0.8) +
  scale_linetype_manual(values = c(1, 6)) +
  # scale_x_continuous(expand = c(0, NA),
  #                    breaks = seq(0, 9000, 600)) +
  #scale_y_continuous(breaks = seq(0, 160, 5)) + 
  labs(x = "Time (in Seconds)",
       y = "",
       subtitle = "Linear Estimation") +
  theme_apa() +
  theme(axis.title.y = element_blank()) +
  facet_grid(cols = vars(time_span),
             scales = "free_x")

ki_plot_phases <-
  main %>% 
  filter(time_span != "overall") %>%
  dplyr::select("ID","time_span", "time","heart_rate_std") %>% 
  mutate(time_span = factor(time_span,
                            levels = c("preparation","teaching","post","interview","end"),
                            labels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase"))) %>% 
  distinct() %>%
  group_by(time_span) %>% 
  summarise(z_mean = mean(heart_rate_std),
            z_sd = sd(heart_rate_std),
            z_t = qt(p = 0.01 / 2,      # 0.01 KI
               df = n() - 1,
               lower.tail = F
               ),
            z_error = z_sd / sqrt(n()),
            lower = z_mean - z_t * z_error,
            upper = z_mean + z_t * z_error,
            ) %>% 
  ungroup() %>% 
  ggplot(mapping = aes(x = factor(0),
                       y = z_mean)) + 
  geom_point() +
  geom_errorbar(mapping = aes(ymin = lower,
                              ymax = upper),
                width = 0.2) +
  geom_hline(yintercept = 0,
             linetype = "dashed") +
  labs(subtitle = "1% Confidence Intervall",
       x = "") +
  facet_grid(cols = vars(time_span)) +
  theme_apa() +
  theme(axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank())


text_y <- text_grob("Average Heart Rate (Standardized)",
                   rot = 90)

plot_overall <-
  grid.arrange(loess_plot_overall, lm_plot_phases, ki_plot_phases,
               ncol = 1,
               left = text_y
               )

plot_overall
```

# Slopes and Intercepts

```{r}
df_regression <- 
  main %>% 
  filter(time_span != "overall") %>%
  dplyr::select("ID", "time_span","time","heart_rate_std","heart_rate") %>% 
  distinct() %>% 
  mutate(time = time / 60) %>% 
  mutate(ID = as_factor(ID),
         Phase = factor(time_span,
                           levels = c("preparation","teaching","post","interview","end"),
                            labels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase")
                           )
         )

fix_models <-
  df_regression %>%
  split(.$Phase) %>%
  map( ~ lm(formula = heart_rate_std ~ 0 + ID + time:ID,
            data = .)) %>%
  map(
    ~ coef(.) %>%
      tibble::as_tibble(.,
                        rownames = "name") %>%
      transmute(
        type = if_else(str_detect(name,
                                  ":"),
                       true = "slope",
                       false = "intercept"),
        id = str_remove_all(name,
                            "[^[:digit:]]"),
        value = value
      ),
    
  ) %>%
  bind_rows(.id = "Phase") %>%
  pivot_wider(names_from = type,
              values_from = value)

p.values_slope <-
  fix_models %>%
  split(.$Phase) %>%
  map( ~ t.test(x = .$slope,
                mu = 0)$p.value) %>%
  bind_rows(.id = "Phase") %>%
  pivot_longer(cols = everything(),
               names_to = "Phase",
               values_to = "p.value_slope")

p.values_intercept <-
  fix_models %>%
  split(.$Phase) %>%
  map( ~ t.test(x = .$intercept,
                mu = 0)$p.value) %>%
  bind_rows(.id = "Phase") %>%
  pivot_longer(cols = everything(),
               names_to = "Phase",
               values_to = "p.value_intercept")

sd_mean <-
  fix_models %>%
  group_by(Phase) %>%
  summarize(
    mean_slope = mean(slope),
    sd_slope = sd(slope),
    mean_intercept = mean(intercept),
    sd_intercept = sd(intercept)
  )

table_data <- 
  right_join(x = sd_mean,
             y = p.values_intercept,
             by = "Phase") %>% 
  right_join(x = .,
             y = p.values_slope,
             by = "Phase") %>% 
  transmute(Phase = factor(Phase,
                           levels = c("Pre Teaching Phase","Teaching Phase","Post Teaching Phase","Interview Phase","End Phase")
                           ),
            n = NA,
            `Mean(Intercept)` = mean_intercept,
            `SD(Intercept)` = sd_intercept,
            `p-Value (Intercept)` = p.value_intercept,
            `Mean(Slope)` = mean_slope, 
            `SD(Slope)` = sd_slope,
            `p-Value (Slope)` = p.value_slope, 
            ) %>% 
  arrange(Phase)

table_data$n[table_data$Phase == "Pre Teaching Phase"] <- df_regression %>% filter(Phase == "Pre Teaching Phase") %>% pull(heart_rate_std) %>% length()
table_data$n[table_data$Phase == "Teaching Phase"] <- df_regression %>% filter(Phase == "Teaching Phase") %>% pull(heart_rate_std) %>% length()
table_data$n[table_data$Phase == "Post Teaching Phase"] <- df_regression %>% filter(Phase == "Post Teaching Phase") %>% pull(heart_rate_std) %>% length()
table_data$n[table_data$Phase == "Interview Phase"] <- df_regression %>% filter(Phase == "Interview Phase") %>% pull(heart_rate_std) %>% length()
table_data$n[table_data$Phase == "End Phase"] <- df_regression %>% filter(Phase == "End Phase") %>% pull(heart_rate_std) %>% length()

table_data %>% 
  knitr::kable(.)
```

# Plots for all phases

```{r}
mods <-   
  df_regression %>% 
  split(.$time_span) %>% 
  map(~ lm(formula = heart_rate_std ~ 0 + ID + time:ID,
       data = .
       )
      )

graph_data <- 
  df_regression %>% 
  split(.$time_span) 

example <- list(mod = mods$preparation, data = graph_data$preparation)


list(`Preparation Phase` = list(name = "Preparation Phase", mod = mods$preparation, data = graph_data$preparation),
     `Teaching Phase` = list(name = "Teaching Phase", mod = mods$teaching, data = graph_data$teaching),
     `Post Teaching Phase` = list(name = "Post Teaching Phase",mod = mods$post, data = graph_data$post),
     `Interview Phase` = list(name = "Interview Phase",mod = mods$interview, data = graph_data$interview),
     `End Phase` = list(name = "End Phase",mod = mods$end, data = graph_data$end)
     ) %>% 
  map(~ ggplot(data = .$data,
               mapping = aes(x = time,
                             y = heart_rate_std,
                             group = ID)) +
        geom_line(mapping = aes(y = fitted(.$mod)),
                  color = "blue",
                  size = 1) +
        geom_point(alpha = 0.5,
                   size = 0.5) +
        labs(title = .$name,
             y = "Heart Rate (Standardized)",
             x = "Time (in Seconds)") +
        facet_wrap( ~ ID, nrow = 6) +
        theme_apa()
      )
```



# t-Tests

using heart rate means

```{r}
df_ttest <- 
  df_regression %>% 
  group_by(ID, time_span) %>% 
  summarize(mean_heart_rate = mean(heart_rate_std)) %>% 
  ungroup()
```


## Teaching vs. Interview

```{r}
df_ttest %$% 
  t.test(x = .$mean_heart_rate[.$time_span == "teaching"],
         y = .$mean_heart_rate[.$time_span == "interview"],
         paired = T)

df_ttest %$% 
  CohenD(x = .$mean_heart_rate[.$time_span == "teaching"],
         y = .$mean_heart_rate[.$time_span == "interview"],
         pooled = T)
```

## teaching vs. end

```{r}
df_ttest %$% 
  t.test(x = .$mean_heart_rate[.$time_span == "teaching"],
         y = .$mean_heart_rate[.$time_span == "end"],
         paired = T)

df_ttest %$% 
  CohenD(x = .$mean_heart_rate[.$time_span == "teaching"],
         y = .$mean_heart_rate[.$time_span == "end"],
         pooled = T)
```

## interview vs. end

```{r}
df_ttest %$% 
  t.test(x = .$mean_heart_rate[.$time_span == "interview"],
         y = .$mean_heart_rate[.$time_span == "end"],
         paired = T)

df_ttest %$% 
  CohenD(x = .$mean_heart_rate[.$time_span == "interview"],
         y = .$mean_heart_rate[.$time_span == "end"],
         pooled = T)
```

# Multiple Linear Regression

# Pre Teaching Phase

```{r}


fit_pre_1 <-
   %>% 
  filter(time_span == "pre") %$% 
  lm(slope ~ mean_disruption)

fit_pre_2 <-
  df_test_reg %>% 
  filter(time_span == "pre") %$% 
  lm(time ~ mean_confidence)

fit_pre_3 <-
  df_test_reg %>% 
  filter(time_span == "pre") %$% 
  lm(time ~ mean_confidence + mean_disruption)

fit_pre_4 <-
  df_test_reg %>% 
  filter(time_span == "pre") %$% 
  lm(time ~ mean_confidence + mean_disruption + teaching_experience)

stargazer::stargazer(fit_pre_1, fit_pre_2,fit_pre_3, fit_pre_4,
                     type = "latex",
                     caption = "Pre Phase",
                     dep.var.labels = "Slope",
                     order = c(1, 3, 2),
                     covariate.labels = c("Disruption Factor",
                                          "Confidence Factor",
                                          "Teaching Experience"),
                     keep.stat = c("n","rsq","adj.rsq")
                     )
```
```

