---
title: "Professional vision - link between eye tracking parameters and the ability
  to generate action alternatives"
output:
  html_document:
    df_print: paged
  pdf_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, warning = FALSE)
```

# load packages and read in data
```{r}
library(needs)
needs(tidyverse,
      psych,
      moments,
      sjPlot,
      DescTools,
      irr,
      readxl, 
      gridExtra,
      janitor,
      RColorBrewer,
      cowplot)

# suppress "summarize" info. 
# if this line is ommitted, each table using the summarize function will be accompanied with a warning from the console
options(dplyr.summarise.inform = FALSE)

### EYE TRACKING DATA 

# return a character vector with names of .tsv data in data folder
file_names <- list.files(path = "data",
                         pattern = "interval_complete.tsv")

# read every object names in file_names and save it as a tibble
for (i in file_names) {
  
  work_data <- 
    read_tsv(file = paste0("data/", i),
             locale = locale(decimal_mark = ","))
  
  assign(value = work_data,
         x = str_remove(paste0("tib_", i),
                        pattern = ".tsv"
         )
  )
  
}

# Bind every tibble that contains "interval_complete" to a new tible
df_aoi <- 
  mget(ls(pattern = "interval_complete")) %>%
  bind_rows()

# Remove temporary data for a cleaner workspace
rm(list = ls(pattern = "^tib_ProVisio"))
rm(work_data)
rm(file_names)
rm(i)

### TIME TO FIRST FIXATION 
df_aoi %>% 
  filter(TOI == "Chatting_with_neighbour") %>% 
  select (Participant, 
          "Time_to_first_fixation.Disruptive_Person") %>% 
  rowwise() %>% 
  mutate(ID = str_extract(string = Participant,
                          pattern = "[:digit:]{3}"),
         ID = as.numeric(ID)
         
         # Disrup_time_fixation_sec = round(Time_to_first_fixation.Disruptive_Person / 1000,digits = 2)#changing milliseconds into seconds
         ) %>% 
  select(ID,
         Time_to_first_fixation.Disruptive_Person) %>% 
  janitor::clean_names() -> df_ttff_disrup
  # filter(!ID %in% c(204)) 


# SELF-REPORT DATA
df_sri <- 
  excel_sheets("data/coding_sri.xlsx") %>% 
  map_df(~read_xlsx("data/coding_sri.xlsx",.)) %>% 
  dplyr::select(ID, Event, `Confidence Factor`) %>% 
  filter(
    # ID %in% c(101:125, 202:217),
         Event %in% c("chatting")) %>%
  janitor::clean_names()


# ACTION ALTERNATIVES
df_alternatives <- read_excel("data/coding_action_alternatives.xlsx") %>% 
  janitor::clean_names() %>% 
  group_by(id) %>% 
  mutate(mean_code = mean(code)) %>% 
  distinct(count, mean_code)


# merge data frames
# put all data frames into list
df_list <- list(df_ttff_disrup, df_sri, df_alternatives)

# merge all data frames in list
main <-
  df_list %>% reduce(full_join, by='id') %>%
  janitor::clean_names() %>%
  select(!event) %>% # select relevant columns
  na.omit()

main$id = ifelse(main$id < 200, "Novice","Expert")

```


# descriptives
```{r}
# main %>%
#   distinct() %>%
#   group_by(id) %>%
#   summarize(mean_ttff = round(mean(time_to_first_fixation_disruptive_person), digits = 0),
#             sd_ttff = round(sd(time_to_first_fixation_disruptive_person), digits = 0),
#             mean_confi = round(mean(confidence_factor), digits = 0),
#             sd_confi = round(sd(confidence_factor), digits = 0),
#             mean_aa_count = round(mean(count), digits = 0),
#             sd_aa_count = round(sd(count), digits = 0),
#             mean_aa_code = round(mean(mean_code), digits = 0),
#             sd_aa_code = round(sd(mean_code), digits = 0)) %>%
#   ungroup() -> df_descriptives

# time_to_first_fixation_disruptive_person
describeBy(main$time_to_first_fixation_disruptive_person, main$id)
plot_ttff <- boxplot(time_to_first_fixation_disruptive_person ~ id, data = main)

# confidence factor
describeBy(main$confidence_factor, main$id)
plot_confi <- boxplot(confidence_factor ~ id, data = main)

# action alternatives - count
describeBy(main$count, main$id)
plot_action_count <- boxplot(count ~ id, data = main)

# action alternatives - quality  
describeBy(main$mean_code, main$id)
plot_action_quality <- boxplot(mean_code ~ id, data = main)

```

# t-test and effect size

```{r}
### time to first fixation on disruptive person

df_ttff_disrup$id = ifelse(df_ttff_disrup$id < 200, "Novice","Expert")

# t-test for expertise differences
t.test(x = df_ttff_disrup$time_to_first_fixation_disruptive_person[df_ttff_disrup$id == "Expert"],
                     y = df_ttff_disrup$time_to_first_fixation_disruptive_person[df_ttff_disrup$id == "Novice"])


# effect size for expertise differences
CohenD(x = df_ttff_disrup$time_to_first_fixation_disruptive_person[df_ttff_disrup$id == "Expert"],
                 y = df_ttff_disrup$time_to_first_fixation_disruptive_person[df_ttff_disrup$id == "Novice"],
                 na.rm = TRUE)

#### sri - confidence factor

df_sri$id = ifelse(df_sri$id < 200, "Novice","Expert")

# t-test for expertise differences
t.test(x = df_sri$confidence_factor[df_sri$id == "Expert"],
                    y = df_sri$confidence_factor[df_sri$id == "Novice"])

# effect size for expertise differences
CohenD(x = df_sri$confidence_factor[df_sri$id == "Expert"],
                y = df_sri$confidence_factor[df_sri$id == "Novice"],
                na.rm = TRUE)

### action alternatives count

df_alternatives$id = ifelse(df_alternatives$id < 200, "Novice","Expert")

# t-test for expertise differences
t.test(x = df_alternatives$count[df_alternatives$id == "Expert"],
                         y = df_alternatives$count[df_alternatives$id == "Novice"])

# effect size for expertise differences
CohenD(x = df_alternatives$count[df_alternatives$id == "Expert"],
                     y = df_alternatives$count[df_alternatives$id == "Novice"],
                     na.rm = TRUE)

### action alternatives code
# Mann-Whitney-U-Test
wilcox.test(main$mean_code ~ main$id) 

# t-test for expertise differences
t.test(x = df_alternatives$mean_code[df_alternatives$id == "Expert"],
                        y = df_alternatives$mean_code[df_alternatives$id == "Novice"])

# effect size for expertise differences
CohenD(x = df_alternatives$mean_code[df_alternatives$id == "Expert"],
                    y = df_alternatives$mean_code[df_alternatives$id == "Novice"],
                    na.rm = TRUE)
```

# confidence factor x count of action alternatives
```{r}
main %>% 
  filter(!is.na(confidence_factor) | !is.na(count)) %>% 
  # filter(id %in% c("Novice")) %>% 
  ggplot(mapping = aes(x = confidence_factor,
                       y = count,
                       colour = id
                       )
         ) +
  geom_point() + 
  geom_smooth(method = "lm",
              se = TRUE) +
  scale_color_viridis_d() +
  labs(x = "Confidence Factor",
       y = "Count of action alternatives") +
  theme_cowplot()

```
# confidence factor x quality of action alternatives

```{r}
main %>% 
  filter(!is.na(confidence_factor) | !is.na(mean_code)) %>% 
  # filter(id %in% c("Novice")) %>% 
  ggplot(mapping = aes(x = confidence_factor,
                       y = mean_code,
                       colour = id
                       )
         ) +
  geom_point() + 
  geom_smooth(method = "lm",
              se = TRUE) +
  scale_color_viridis_d() +
  labs(x = "Confidence Factor",
       y = "Quality of action alternatives (Code1-6)") + 
  theme_cowplot()

```


# time to first fixation x count of action alternatives
```{r}
main %>% 
  filter(!is.na(time_to_first_fixation_disruptive_person) | !is.na(count)) %>% 
  # filter(id %in% c("Novice")) %>% 
  ggplot(mapping = aes(x = time_to_first_fixation_disruptive_person,
                       y = count,
                       colour = id
                       )
         ) +
  geom_point() +
  geom_smooth(method = "lm",
              se = TRUE) +
  scale_color_viridis_d() +
  labs(x = "Time to first fixation on disruptive person",
       y = "Count of action alternatives") + 
  theme_cowplot()

```

# time to first fixation x quality of action alternatives
```{r}
main %>% 
  filter(!is.na(time_to_first_fixation_disruptive_person) | !is.na(mean_code)) %>% 
  # filter(id %in% c("Novice")) %>% 
  ggplot(mapping = aes(x = time_to_first_fixation_disruptive_person,
                       y = mean_code,
                       colour = id
                       )
         ) +
  geom_point() +
  geom_smooth(method = "lm",
              se = TRUE) +
  scale_color_viridis_d() +
  labs(x = "Time to first fixation on disruptive person",
       y = "Quality of action alternatives (Code1-6)") + 
  theme_cowplot()

```

# count x quality of action alternatives
```{r}
main %>% 
  filter(!is.na(count) | !is.na(mean_code)) %>% 
  # filter(id %in% c("Novice")) %>% 
  ggplot(mapping = aes(x = count,
                       y = mean_code,
                       colour = id
                       )
         ) +
  geom_point() +
  geom_smooth(method = "lm",
              se = TRUE) +
  scale_color_viridis_d() +
  labs(x = "Count of action alternatives",
       y = "Quality of action alternatives (Code1-6)") + 
  theme_cowplot()

```

# pearson & spearman correlation

```{r}
# novices: correlation between confidence factor and count
main %>% 
  filter(id %in% c("Novice")) -> corr.nov

cor.test(corr.nov$confidence_factor, corr.nov$count, method=c("pearson"))

# experts: correlation between confidence factor and count
main %>% 
  filter(id %in% c("Expert")) -> corr.exp

cor.test(corr.exp$confidence_factor, corr.exp$count, method=c("pearson"))

# novices: correlation between confidence factor and quality
cor.test(corr.nov$confidence_factor, corr.nov$mean_code, method=c("spearman"))

# experts: correlation between confidence factor and quality
cor.test(corr.exp$confidence_factor, corr.exp$mean_code, method=c("spearman"))

# novices: correlation between time to first fixation and count
cor.test(corr.nov$time_to_first_fixation_disruptive_person, corr.nov$count, method=c("pearson"))

####### experts: correlation between time to first fixation and count
cor.test(corr.exp$time_to_first_fixation_disruptive_person, corr.exp$count, method=c("pearson"))

# novices: correlation between time to first fixation and quality
cor.test(corr.nov$time_to_first_fixation_disruptive_person, corr.nov$mean_code, method=c("spearman"))

# experts: correlation between time to first fixation and quality
cor.test(corr.exp$time_to_first_fixation_disruptive_person, corr.exp$mean_code, method=c("spearman"))

# novices: correlation between count and quality
cor.test(corr.nov$count, corr.nov$mean_code, method=c("spearman"))

# experts: correlation between count and quality
cor.test(corr.exp$count, corr.exp$mean_code, method=c("spearman"))

```

