---
title: "EMU Questionnaire - Item & Scale Analysis"
output:
  pdf_document: default
  html_notebook: default
---

```{r include=FALSE}
# install.packages("needs")

# suppress "summarize" info. 
# if this line is ommitted, each table using the summarize function will be accompanied with a warning from the console
options(dplyr.summarise.inform = FALSE)

library(needs)
needs(tidyverse,
      lubridate,
      viridis,
      grid,
      gridExtra,
      cowplot,
      readxl,
      ARTofR,
      moments,
      ltm,
      sjPlot,
      kableExtra,
      xtable,
      DescTools,
      formattable,
      psych)

```


# Presence Questionnaire

After each micro-teaching-unit, participants answered items on teaching quality using a validated questionnaire [@helmke2014unterrichtsdiagnostik] and self developed scales on the teacher's presence behavior derived from the research literature. The questionnaire was a 4-point Likert scale (1 = Strongly Disagree; 4 = Strongly Agree).

```{r presence_questionnaire, echo=FALSE, results=TRUE}

# original scale analysis

# load data files
quest.data <- read_excel("./data/data_empschul_labor_lehrperson.xlsx") %>%
  dplyr::select(LB01_01:LB01_03,
                LM01_01,
                LM01_03:LM01_08,
                LP01_01:LP01_08,
                LV01_01:LV01_03) 

# descriptive data
describe(quest.data)

# omega
omega(quest.data)

# creating a matrix
quest.table <- matrix(data = NA, nrow = 4, ncol = 8)
rownames(quest.table) <- c("LM", "LB", "LP", "LV")
colnames(quest.table) <- c("N Items","M","SD","Min","Max","Skewness","Kurtosis","Alpha")

# creating a loop
i <- "LM"

for (i in c("LM", "LB", "LP", "LV")) {

loop.data <- quest.data %>%
  dplyr::select(starts_with(match = i))

quest.table[i, "N Items"] <- length(loop.data)

# calculating mean
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  mean() %>%
  round(., digits = 2) ->
quest.table[i, "M"]

# calculating SD
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  sd() %>%
  round(., digits = 2) ->
quest.table[i, "SD"]

# calculating Min
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  min() %>%
  round(., digits = 2) ->
quest.table[i, "Min"]

# calculating Max
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  max() %>%
  round(., digits = 2) ->
quest.table[i, "Max"]

# calculating Skewness
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  skewness() %>%
  round(., digits = 2) ->
quest.table[i, "Skewness"]

# calculating Kurtosis
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  kurtosis() %>%
  round(., digits = 2) ->
quest.table[i, "Kurtosis"]

# calculating Alpha
alpha <- loop.data %>%
  cronbach.alpha()

quest.table[i, "Alpha"] <- round(alpha$alpha,2)

}

# rename columns
rownames(quest.table) <- c("Classroom Management", "Balance", "Presence", "Natural Behavior")

# format and insert table in manuscript
papaja::apa_table(
quest.table,
  caption = "Scale analysis for teachers' self-assessment",
  # note = "Write Note here",
  escape = TRUE, # if TRUE special Latex characters are escaped; if this is turned to F captions cannot be rendered. I don't know why...
  placement = "h", # position of table in page:  exact location (h), at the top (t), bottom (b)
  font_size = "tiny" # options are tiny, scriptsize, footnotesize, small, normalsize (default), large, Large, LARGE, huge, Huge
)


# load data files with modified sclaes
quest.data <- read_excel("./data/data_empschul_labor_lehrperson.xlsx") %>%
  dplyr::select(LB01_01:LB01_03,
                LM01_01:LM01_08,
                LP01_01:LP01_08,
                LV01_01:LV01_03) %>% 
  rename(
    LZ01_06 = LM01_06,
    LZ01_07 = LM01_07,
    LZ01_08 = LM01_08
    )

# descriptive data
describe(quest.data)

# omega
omega(quest.data)

# creating a matrix
quest.table <- matrix(data = NA, nrow = 5, ncol = 8)
rownames(quest.table) <- c("LM", "LB", "LP", "LV", "LZ")
colnames(quest.table) <- c("N Items","M","SD","Min","Max","Skewness","Kurtosis","Alpha")

# creating a loop
i <- "LM"

for (i in c("LM", "LB", "LP", "LV", "LZ")) {

loop.data <- quest.data %>%
  dplyr::select(starts_with(match = i))

quest.table[i, "N Items"] <- length(loop.data)

# calculating mean
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  mean() %>%
  round(., digits = 2) ->
quest.table[i, "M"]

# calculating SD
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  sd() %>%
  round(., digits = 2) ->
quest.table[i, "SD"]

# calculating Min
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  min() %>%
  round(., digits = 2) ->
quest.table[i, "Min"]

# calculating Max
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  max() %>%
  round(., digits = 2) ->
quest.table[i, "Max"]

# calculating Skewness
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  skewness() %>%
  round(., digits = 2) ->
quest.table[i, "Skewness"]

# calculating Kurtosis
loop.data %>%
  mutate(mean = rowMeans(.)) %>%
  pull(mean) %>%
  kurtosis() %>%
  round(., digits = 2) ->
quest.table[i, "Kurtosis"]

# calculating Alpha
alpha <- loop.data %>%
  cronbach.alpha()

quest.table[i, "Alpha"] <- round(alpha$alpha,2)

}

# rename columns
rownames(quest.table) <- c("Classroom Management", "Balance", "Presence", "Natural Behavior", "Additional")

# format and insert table in manuscript
papaja::apa_table(
quest.table,
  caption = "Scale analysis for teachers' self-assessment",
  # note = "Write Note here",
  escape = TRUE, # if TRUE special Latex characters are escaped; if this is turned to F captions cannot be rendered. I don't know why...
  placement = "h", # position of table in page:  exact location (h), at the top (t), bottom (b)
  font_size = "tiny" # options are tiny, scriptsize, footnotesize, small, normalsize (default), large, Large, LARGE, huge, Huge
)

```

```{r item_analysis_classroom_management, echo=FALSE, results='asis'}
quest.data %>%
  dplyr::select(contains("LM")) %>%
  as.data.frame() %>%
  tab_itemscale(CSS = list(
    css.firsttablerow.col7 = "'cronbachs alpha';"
  ))
```

```{r item_analysis_balance, echo=FALSE, results='asis'}
quest.data %>%
  dplyr::select(contains("LB")) %>%
  as.data.frame() %>%
  tab_itemscale()
```

```{r item_analysis_presence, echo=FALSE, results='asis'}
quest.data %>%
  dplyr::select(contains("LP")) %>%
  as.data.frame() %>%
  tab_itemscale()
```

```{r item_analysis_behavior, echo=FALSE, results='asis'}
quest.data %>%
  dplyr::select(contains("LV")) %>%
  as.data.frame() %>%
  tab_itemscale()
```

```{r item_analysis_additional, echo=FALSE, results='asis'}
quest.data %>%
  dplyr::select(contains("LZ")) %>%
  as.data.frame() %>%
  tab_itemscale()
```
